version: "3.8"

services:
  db:
    image: postgres:12-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: hallo123!
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
